# Generated by Django 3.2.13 on 2022-05-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_data_migration_2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interim_news",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField(blank=True, null=True, verbose_name="Interim_body")),
            ],
        ),
    ]
