# Generated by Django 3.2.13 on 2022-05-28 20:32

from django.db import migrations


def delete_func(apps, schema_editor):
    News = apps.get_model("mainapp", "News")
    list_of_ids = News.objects.values_list("id", flat=True)
    for item_id in list_of_ids:
        News.objects.update_or_create(id=item_id, defaults={"body": None})


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_news_data_transfer"),
    ]

    operations = [migrations.RunPython(delete_func)]
