# Generated by Django 3.2.13 on 2022-05-28 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0010_news_data_transfer_back"),
    ]

    operations = [migrations.DeleteModel("Interim_news")]
