# Generated by Django 3.2.13 on 2022-06-16 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0013_coursefeedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courses",
            options={"ordering": ("-created",), "verbose_name": "Course", "verbose_name_plural": "Courses"},
        ),
    ]
