# Generated by Django 3.2.13 on 2022-06-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0014_alter_courses_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courses",
            options={"ordering": ("created",), "verbose_name": "Course", "verbose_name_plural": "Courses"},
        ),
    ]
